import streamlit as st
from pbixray import PBIXRay
from dotenv import load_dotenv
from anthropic import Anthropic
import tempfile, os

load_dotenv()
client = Anthropic()

st.set_page_config(page_title="Power BI AI Documentation Generator", layout="wide")
st.title("AI-Powered Power BI Documentation Generator")
st.write("Upload a .pbix file and get plain-English documentation for every DAX measure, generated by Claude.")

PROMPT_TEMPLATE = """You are a senior BI developer writing documentation for a colleague.

Table: {table}
Measure name: {name}
DAX expression:
{dax}

Write:
1. A one-sentence plain-English description of what this measure calculates.
2. A one-line note on anything risky or unclear (or "No obvious issues.").
Keep the whole answer under 60 words."""

uploaded_file = st.file_uploader("Upload a .pbix file", type=["pbix"])

if uploaded_file is not None:
    # pbixray needs a real file path, so save the upload to a temp file first
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pbix") as tmp:
        tmp.write(uploaded_file.read())
        tmp_path = tmp.name

    model = PBIXRay(tmp_path)
    measures = model.dax_measures
    st.success(f"Found {len(measures)} measures across {len(model.tables)} tables.")

    if st.button("Generate documentation"):
        progress = st.progress(0)
        for i, (index, row) in enumerate(measures.iterrows()):
            prompt = PROMPT_TEMPLATE.format(
                table=row["TableName"], name=row["Name"], dax=row["Expression"]
            )
            response = client.messages.create(
                model="claude-haiku-4-5",
                max_tokens=300,
                messages=[{"role": "user", "content": prompt}]
            )
            explanation = response.content[0].text.strip()

            with st.expander(f"[{row['TableName']}] {row['Name']}"):
                st.code(row["Expression"], language="sql")
                st.write(explanation)

            progress.progress((i + 1) / len(measures))

    os.remove(tmp_path)